arduino:
  msg_buff: 9600
  port: /dev/cu.usbmodem1433301
  #port: /dev/cu.usbmodem141201
  sleep_msg:  0.001 #50
  time_msg_interval: 1.0
servo_spec:
  home: [ 1400, 2020, 1527, 1465, 2072, 800 ]
  max: [ 2400, 2400, 1950, 2500, 2500, 1700 ]
  min: [ 600, 1500, 1150, 500, 500, 800 ]
#  pwm_min: [600, 600, 600, 500, 500, 500]
#  pwm_max: [2400, 2400, 2400, 2500, 2500, 2500]
  pwm_min: [ 600, 700, 700, 850, 500, 500 ]
  pwm_max: [ 2400, 2300, 2300, 2150, 2500, 2500 ]
  angle_max: [2826, 2826, 2826, 900, 300, 180]
  gear_ratio: [9, 7, 5, 4, 2, 1]
  servo_direction: [-1, -1, 1, 1, -1, 1]
video_stream:
  camera_id: 1
  fps: 10
  width_target: 320
kinematics:
  link_size: [14.3, 14.5, 14.5, 0, 0, 6, 19.5]
  theta0: [0, 0, 0, 0, 0]
  z_limit: 5
  enable_collision: False
  gripper_state: None
obj_detection:
    min_obj_size: 300


